version: 2
jobs:
  test_houses_pipeline:
  working_directory: ~/project
  docker:
    - image: continuumio/miniconda3:4.12.0
  steps:
    - checkout
    - run:
      name: Running Houses pipeline tests
      command: |
        conda init bash
        source ~/.bashrc
        conda env create -f environment.yml
        conda activate houses
        chmod +x ./houses_pipeline/fetch/fetch_dataset.py
        mkdir data
        mkdir data/raw data/processed data/interim
        # TODO change that to use the make file
        ./houses_pipeline/fetch/fetch_dataset.py data/raw
        pytest houses_pipeline

workflows:
  version: 2
  test-all:
    - jobs:
      - test_houses_pipeline
