version: 2.0
jobs:
  test_houses_pipeline:
    working_directory: ~/project
    docker:
      - image: continuumio/miniconda3:latest
    steps:
      - checkout
      - run:
          name: all
          command: |
            conda init bash
            source ~/.bashrc
            conda env create -f environment.yml
            conda activate houses
            mkdir -p data/processed data/interim
            mkdir -p models logs
            pytest houses_pipeline

workflows:
  version: 2
  test-all:
    jobs:
      - test_houses_pipeline
