version: 2.1

executors:
  docker-python-container:
    docker:
      - image: circleci/python:3.9.5

commands:
  prepare_virtual_environment:
    steps:
      - run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

  install_requirements:
    steps:
      - run:
          . venv/bin/activate
          apt-get update && apt-get install make
          pip install -r houses_pipeline/requirements.txt

  prepare_tox:
    steps:
      - run: |
          sudo pip install --upgrade pip
          pip install --user tox
  say_hello:
    steps:
      - run: |
          make say_hello
  run_tests:
    steps:
      - run: |
          . venv/bin/activate
          pytest .

jobs:
  setup_and_run_tests:
    executor: docker-python-container
    working_directory: ~/project
    steps:
      - checkout
      - prepare_virtual_environment
      - install_requirements
      - run_tests

# TODO: add build workflow
workflows:
  version: 2
  houses_workflow:
    jobs:
      - setup_and_run_tests:
          context:
            - kaggling
            - gemfury
