version: 2.1

executors:
  docker-conda-executor:
    docker:
      - image: circleci/python:3.9.5

commands:
  prepare_pipeline_virtual_environment:
    steps:
      - run: |
          python3 -m venv pipeline_venv
          source pipeline_venv/bin/activate
          pip install --upgrade pip

  install_pipeline_requirements:
    steps:
      - run: |
          . pipeline_venv/bin/activate
          pip install -r houses_pipeline/requirements.txt

  prepare_tox:
    steps:
      - run: |
          sudo pip install --upgrade pip
          pip install --user tox

  update:
    steps:
      - run: |
          apt-get update -y
          apt-get install make
          apt-get install unzip

  run_houses_pipeline_tests:
    description: "Run houses_pipeline tests"
    steps:
      - run: |
          . pipeline_venv/bin/activate
          pytest houses_pipeline

jobs:
  setup_and_run_tests:
    executor: docker-conda-executor
    working_directory: ~/project
    docker:
      - image: continuumio/miniconda3:latest
    steps:
      - checkout
      - update

      - prepare_pipeline_virtual_environment
      - install_pipeline_requirements
      - run_houses_pipeline_tests

workflows:
  version: 2
  houses_workflow:
    jobs:
      - setup_and_run_tests:
          context:
            - kaggling
            - gemfury
