defaults: &defaults
  docker:
    - image: continuumio/miniconda3:latest
  working_directory: ~/project

prepare_conda_environment: &prepare_conda_environment
  run:
    name: Prepare Conda Environment
    command: |
      conda init bash
      source ~/.bashrc
      conda env create -f environment.yml
      conda activate houses

version: 2.0
jobs:
  test_houses_pipeline:
    working_directory: ~/project
    docker:
      - image: continuumio/miniconda3:latest
    steps:
      - checkout
      - *prepare_conda_environment
      - run:
          name: all
          command: |
            mkdir -p data/processed data/interim
            mkdir -p models logs
            pytest houses_pipeline

workflows:
  version: 2
  test-all:
    jobs:
      - test_houses_pipeline
