version: 2.1

executors:
  docker-python-executor:
    docker:
      - image: circleci/python:3.9.5

commands:
  update:
    description: "Installing ubuntu prerequisites"
    steps:
      - run: |
          apt-get update -y
          apt-get install make
          apt-get install unzip

  prepare_pipeline_virtual_environment:
    description: "Preparing the pipeline virtual environment"
    steps:
      - run: |
          python3 -m venv pipeline_venv
          source pipeline_venv/bin/activate
          pip install --upgrade pip

  install_pipeline_requirements:
    description: "Installing pipeline requirements"
    steps:
      - run: |
          . pipeline_venv/bin/activate
          pip install -r houses_pipeline/requirements.txt

  run_pipeline_tests:
    description: "Run pipeline tests"
    steps:
      - run: |
          . pipeline_venv/bin/activate
          pytest houses_pipeline

  prepare_api_virtual_environment:
    description: "Preparing the api virtual environment"
    steps:
      - run: |
          python3 -m venv api_venv
          source api_venv/bin/activate
          pip install --upgrade pip

  install_api_requirements:
    description: "Installing API requirements"
    steps:
      - run: |
          . api_venv/bin/activate
          pip install -r houses_api/requirements.txt

  run_api_tests:
    description: "Run api tests"
    steps:
      - run: |
          . api_venv/bin/activate
          pytest houses_api

  prepare_tox:
    steps:
      - run: |
          sudo pip install --upgrade pip
          pip install --user tox

jobs:
  setup_and_run_tests:
    executor: docker-python-executor
    working_directory: ~/project
    steps:
      - checkout
      - update
      # houses_pipeline testing and setting
      - prepare_pipeline_virtual_environment
      - install_pipeline_requirements
      - run_pipeline_tests
      # api testing and setting
      - prepare_api_virtual_environment
      - install_api_requirements
      - run_api_tests

workflows:
  version: 2
  houses_workflow:
    jobs:
      - setup_and_run_tests:
          context:
            - kaggling
            - gemfury
