version: 2.0
commands:
  activate_conda:
    steps:
      - run:
        name: activate_conda
        command: |
          conda init bash
                source ~/.bashrc
                conda env create -f environment.yml
                conda activate houses
  
  run_tests:
    steps:
      - run:
        name: run_tests
        command: |
          pytest houses_pipeline
          pytest houses_api
jobs:
  setup_and_run_tests:
    working_directory: ~/project
    docker:
      - image: continuumio/miniconda3:latest
    steps:
      - checkout
      - activate_conda
      # - TODO: ADD this fetch_dataset
      - run_tests
      - run_api_tests

workflows:
  version: 2
  houses_workflow:
    jobs:
      - setup_and_run_tests
