version: 2.1

executors:
  docker-conda-executor:
    docker:
      - image: continuumio/miniconda3:latest

commands:
  create_conda_environment:
    steps:
      - run: |
          conda init bash
          source ~/.bashrc
          conda env create -f environment.yml

  activate_conda_environment:
    steps:
      - run: |
          conda init bash
          source ~/.bashrc
          conda activate houses


  run_tests:
    steps:
      - activate_conda_environment
      - run: |
          conda init bash
          source ~/.bashrc
          conda activate houses
          make test

jobs:
  setup_and_run_tests:
    executor: docker-conda-executor
    working_directory: ~/project
    docker:
      - image: continuumio/miniconda3:latest
    steps:
      - checkout
      - create_conda_environment
      - run_tests

# TODO: add build workflow
workflows:
  version: 2
  houses_workflow:
    jobs:
      - setup_and_run_tests:
          context:
            - kaggling
            - gemfury
