version: 2.1

executors:
  docker-python-executor:
    docker:
      - image: circleci/python:3.9.5

commands:
  update:
    description: "Installing ubuntu prerequisites"
    steps:
      - run: |
          sudo apt-get update -y
          sudo apt-get install make
          sudo apt-get install unzip

  prepare_pipeline_virtual_environment:
    description: "Preparing the pipeline virtual environment"
    steps:
      - run: |
          python3 -m venv pipeline_venv
          source pipeline_venv/bin/activate
          pip install --upgrade pip

  install_pipeline_requirements:
    description: "Installing pipeline requirements"
    steps:
      - run: |
          . pipeline_venv/bin/activate
          pip install -r requirements.txt

  run_pipeline_lint:
    description: "Run pipeline linting"
    steps:
      - run: |
          . pipeline_venv/bin/activate
          make lint
  
  run_pipeline_tests:
    description: "Run pipeline tests"
    steps:
      - run: |
          . pipeline_venv/bin/activate
          make test

  train_and_publish_houses_model:
    description: "Train the houses model"
    steps:
      - run: |
          . pipeline_venv/bin/activate
          make train
          make publish

  prepare_api_virtual_environment:
    description: "Preparing the api virtual environment"
    steps:
      - run: |
          python3 -m venv api_venv
          source api_venv/bin/activate
          pip install --upgrade pip

  install_api_requirements:
    description: "Installing API requirements"
    steps:
      - run: |
          . api_venv/bin/activate
          pip install -r houses_api/requirements.txt

  run_api_tests:
    description: "Run api tests"
    steps:
      - run: |
          . api_venv/bin/activate
          pytest houses_api

  prepare_tox:
    steps:
      - run: |
          sudo pip install --upgrade pip
          pip install --user tox

jobs:
  setup_and_test_houses_pipeline:
    executor: docker-python-executor
    working_directory: ~/project/pipeline
    steps:
      - checkout
      - update
      # houses_pipeline testing and setting
      - prepare_pipeline_virtual_environment
      - install_pipeline_requirements
      - run_pipeline_tests
      - train_and_publish_houses_model

  setup_and_test_houses_api:
    executor: docker-python-executor
    working_directory: ~/project/api
    steps:
      - checkout
      - update
      # api testing and setting
      - prepare_api_virtual_environment
      - install_api_requirements
      - run_api_tests

  train_and_upload_houses_model:
    executor: docker-python-executor
    working_directory: ~/project
    steps:
      - checkout
      - update
      - prepare_houses_virtual_environment
      - install_houses_requirements
      - train_houses_model

workflows:
  version: 2
  houses_workflow:
    jobs:
      - setup_and_test_houses_pipeline:
          context:
            - kaggling
            - gemfury
      # - setup_and_test_houses_api:
      #     context:
      #       - kaggling
      #       - gemfury
