version: 2.1

executors:
  docker-conda-executor:
    docker:
      - image: circleci/python:3.9.5

commands:
  prepare_virtual_environment:
    steps:
      - run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip

  prepare_tox:
    steps:
      - run: |
          sudo pip install --upgrade pip
          pip install --user tox
  say_hello:
    steps:
      - run: |
          make say_hello

  create_conda_environment:
    steps:
      - run: |
          conda init bash
          source ~/.bashrc
          conda env create -f environment.yml

  activate_conda_environment:
    steps:
      - run: |
          conda init bash
          source ~/.bashrc
          conda activate houses
  update:
    steps:
      - run: |
          apt-get update && apt-get install make

  run_tests:
    steps:
      - activate_conda_environment
      - run: |
          conda init bash
          source ~/.bashrc
          conda activate houses
          make test

jobs:
  setup_and_run_tests:
    executor: docker-conda-executor
    working_directory: ~/project
    docker:
      - image: continuumio/miniconda3:latest
    steps:
      - checkout
      - update
      - say_hello
      # - create_conda_environment
      # - run_tests

# TODO: add build workflow
workflows:
  version: 2
  houses_workflow:
    jobs:
      - setup_and_run_tests:
          context:
            - kaggling
            - gemfury
