version: 2.1
executors:
  docker-conda-executor:
    docker:
      - image: continuumio/miniconda3:latest

commands:
  activate_conda:
    steps:
      - run: |
          conda init bash
          source ~/.bashrc
          conda env create -f environment.yml
          conda activate houses
  run_tests:
    steps:
      - run: |
          conda init bash
          source ~/.bashrc
          conda activate houses
          pytest houses_pipeline
          pytest houses_api

  train_lasso_model:
    steps:
      - checkout
      - run: |
          conda init bash
          source ~/.bashrc
          conda activate houses
          pip install .
          python ./houses_pipeline/modelling/train_lasso.py
jobs:
  setup_and_run_tests:
    executor: docker-conda-executor
    working_directory: ~/project
    docker:
      - image: continuumio/miniconda3:latest
    steps:
      - checkout
      - activate_conda
      # - TODO: ADD this fetch_dataset
      - train_lasso_model
      - run_tests

# TODO: add build workflow
workflows:
  version: 2
  houses_workflow:
    jobs:
      - setup_and_run_tests
